import React from 'react';

// Components
import SEO from './../common/SEO';

// Styles
import './../../assets/css/docpage.css';

// One playable figure. Served from /demos/vosim/<name>/index.html (explicit file:
// a trailing slash falls through to the SPA and returns the shell). The demos are
// generated by scripts/vosim/build.mjs from one shared core, which is also what
// scripts/vosim/test.mjs checks against the formulas below.
function Demo({ name, num, title, children }) {
  return (
    <figure>
      <iframe src={`/demos/vosim/${name}/index.html?compact=1`} loading="lazy"
              title={`${title}, interactive`} />
      <figcaption>
        <span className="doc-fignum">Fig. {num}</span>
        <b>{title}.</b> {children}{' '}
        <a href={`/demos/vosim/${name}/index.html`}>Open full size</a>
      </figcaption>
    </figure>
  );
}

function Vosim() {
  return <div className="docpage">
      <SEO
        title="VOSIM - Bjarni Gunnarsson"
        description="VOSIM, the voice simulation of Kaegi and Tempelaars, rebuilt from Tempelaars's definitions in six playable figures."
        path="/works/docs/vosim"
        noindex={true}
      />
      <h1 className="doc-title">VOSIM</h1>
      <p className="doc-standfirst">
        VOSIM (VOice SIMulation) was developed by Werner Kaegi and Stan Tempelaars at the Institute of Sonology
        in Utrecht in the 1970s. A period of its signal holds a few pulses of squared sine, each lower than the
        one before, followed by silence. Pitch, formant and timbre each have a control of their own, and no filter
        is involved. This page rebuilds the signal from Tempelaars's definitions and lets each part be heard.
      </p>

      <h2 id="signal"><span className="doc-num">1</span>The signal</h2>

      <p>
        A period of length <i>T</i> contains <i>N</i> pulses. Each pulse is a sine squared, which is a raised
        cosine, of width <i>W</i>. The pulses fall in level by a constant ratio <i>b</i>, so that the n-th pulse
        is <i>b<sup>n</sup></i> times the first, and what is left of the period after the last pulse is silence.
        Tempelaars calls the envelope a staircase, "very similar to an exponentially decaying one".
      </p>

      <p className="doc-formula">
        <i>y</i>(<i>t</i>) = <i>e</i>(<i>t</i>) · <i>p</i>(<i>t</i>), &nbsp; <i>p</i>(<i>t</i>) = ½ (1 − cos 2π<i>F</i><i>t</i>), &nbsp; <i>F</i> = 1/<i>W</i>
        <br />
        <i>e</i> = <i>b</i><sup><i>n</i></sup> on pulse <i>n</i> = 0 … <i>N</i>−1, and 0 for the rest of the period
      </p>

      <p>
        The staircase steps fall where the squared sine is zero, so the signal is continuous: there is no click
        at a step. The silence is the zero interval, <i>T</i> − <i>N</i><i>W</i>. When <i>N</i><i>W</i> would exceed
        <i> T</i> the pulses do not fit, and here <i>N</i> is reduced to the number that does.
      </p>

      <Demo name="period" num="1" title="One period">
        The top panel is the signal of the book's figure 4.3.15 (there N = 8 and b = 0.85), and the dashed line is the
        envelope e(t). Below it each harmonic of the signal is a blue line, and the green curve is the closed form of the
        spectral envelope. Try b = 1, where every pulse is as high as the first.
      </Demo>

      <h2 id="pitch"><span className="doc-num">2</span>Pitch and formant</h2>

      <p>
        The repetition rate is <i>1/T</i> and fixes the pitch. The pulse width fixes where the spectrum has its one
        dominant maximum, at <i>F</i> = 1/<i>W</i>. These are separate quantities. Tempelaars gives the amplitude of
        harmonic <i>n</i>, with γ = <i>W</i>/<i>T</i>:
      </p>

      <p className="doc-formula">
        <i>C<sub>n</sub></i> = | sin(π<i>n</i>γ) / (π<i>n</i>(<i>n</i>²γ² − 1)) | · √[ (1 − 2<i>b<sup>N</sup></i> cos 2π<i>N</i><i>n</i>γ + <i>b</i><sup>2<i>N</i></sup>) / (1 − 2<i>b</i> cos 2π<i>n</i>γ + <i>b</i>²) ]
      </p>

      <p>
        The first factor is the spectrum of a single raised-cosine pulse. The second comes from the geometric series
        of the staircase and has its maximum where 2π<i>n</i>γ = 2π, which is <i>n</i>/<i>T</i> = 1/<i>W</i>.
        Changing <i>T</i> moves the harmonics under that hill and changing <i>W</i> moves the hill under the
        harmonics. The spectrum stretches from 0 to roughly 2<i>F</i>, and the higher components are weak.
        This is what Tempelaars means by a formant structure: the spectral envelope does not depend on the
        repetition frequency, as in a vowel.
      </p>

      <Demo name="formant" num="2" title="Pitch and formant">
        Hold the pitch and sweep the formant, then hold the formant and change the pitch. The
        grey outline in the spectrum is the sound you hear, measured live from the audio and scaled to the same
        height as the computed harmonics.
      </Demo>

      <h2 id="decay"><span className="doc-num">3</span>Pulses and decay</h2>

      <p>
        <i>N</i> and <i>b</i> shape the peak. One pulse gives a broad hill, and more pulses narrow it. A ratio
        below 1 lets the staircase die away, which rounds the peak and fills the dips between the lobes. At
        <i> b</i> = 1 the dips reach zero, and any harmonic that falls in one is missing from the signal altogether.
        Tempelaars describes this: if all the pulses have the same height, "the minima extend up to the zero line".
      </p>

      <Demo name="decay" num="3" title="Pulses and decay">
        With T/W = 8, N = 4 and b = 1 only the odd harmonics and the eighth remain. Dots at the bottom of the
        spectrum mark the absent ones.
      </Demo>

      <h2 id="zero"><span className="doc-num">4</span>The zero interval</h2>

      <p>
        The period has the pulses at the start and then silence, and only the silence has to give way when the
        pitch changes. Tempelaars notes that the duty cycle, the proportion of the pulse train to the zero
        interval, is one of the free variables and that, thanks to the zero interval, the period can be
        modulated in a simple way.
      </p>

      <Demo name="zero" num="4" title="Modulating the silence">
        Only the zero interval changes from period to period, and the pulses keep their width. The top panel draws
        four periods from the function the audio uses, and the spectrum shows the harmonics of the unmodulated
        period with the live sound smeared around them.
      </Demo>

      <h2 id="parallel"><span className="doc-num">5</span>Several in parallel</h2>

      <p>
        One VOSIM function has one formant. Combining several with the same period and different pulse widths
        gives a signal with as many formant peaks. Tempelaars describes VOSIM as a direct realisation of the
        modulation model of acoustic communication, "avoiding the nasty problems that can be introduced by
        filters", and compares it with Rodet's CHANT, where several sine bursts with attack and exponential decay
        (FOF) are added in the same way.
      </p>

      <Demo name="vowels" num="5" title="Three formants">
        Three voices share one period. The buttons set typical first, second and third formant frequencies for five
        vowels, approximate male averages after Peterson and Barney (1952). They are an illustration, since
        the VOSIM sources consulted for this page do not give vowel tables.
      </Demo>

      <h2 id="variants"><span className="doc-num">6</span>Three decays</h2>

      <p>
        Implementations differ on how the pulses fall. The original is the staircase above, a constant ratio per
        pulse. The Csound <code>vosim</code> opcode, written by Rasmus Ekman, subtracts a fixed amount from each pulse. The
        SuperCollider <code>VOSIM</code> UGen, by Léon Spek, multiplies by a factor per pulse like the original,
        and its <code>freq</code> is the frequency of the sine inside the square: a pulse is half of its period, so
        W = 1/(2 freq), which is read from the C++ source and not from its help text. The book also gives a
        recursive filter form of a damped raised cosine (its figure 6.3.20), in which the envelope is a smooth
        exponential. With the coefficients as printed there, its impulse response is 1 − cos <i>k</i>γ times
        <i> r<sup>k</sup></i>, twice the function written beside it, so the shape matches and the scale is off by a
        factor of two.
      </p>

      <Demo name="variants" num="6" title="Three ways to decay">
        The same pulse train under the three decays. Only the first is the signal of Tempelaars (1977). The closed-form
        spectrum applies to it alone, so the green curve is hidden for the other two.
      </Demo>

      <h2 id="checks"><span className="doc-num">7</span>What was checked</h2>

      <ul className="doc-checks">
        <li>The spectrum formula was compared with the Fourier coefficients of the signal as defined, for four
          settings of N, γ and b. They agree to 10<sup>−13</sup>, with the constant factor ½ that comes from <i>C<sub>n</sub></i> being a one-sided amplitude.</li>
        <li>The audio worklet was run outside the browser and its harmonics compared with the formula: the largest
          difference is 3 × 10<sup>−7</sup> against a peak of 0.19.</li>
        <li>The period measured 1/T for formants from 600 to 2300 Hz, the peak of the formula stayed within 260 Hz of 1/W for
          three pitches, consecutive pulse levels differed by exactly b, and with b = 1 the predicted harmonics were
          absent to 10<sup>−9</sup>.</li>
        <li>With the zero interval modulated, the first pulse of every period had the same width while the period
          length ranged from 288 to 672 samples.</li>
        <li>In a browser, the live spectrum of the playing audio matched the computed harmonics within one decibel
          for the 22 of the first 24 harmonics that are not exactly zero.</li>
      </ul>

      <p>
        Not read: the original paper of Kaegi and Tempelaars (1978) and Tempelaars's paper on the spectrum (1977),
        both of which this page cites at second hand through the 1996 book. The names and ranges of the original
        hardware controls, and the MIDIM system around it, are not covered.
      </p>

      <h2 id="references"><span className="doc-num">8</span>References</h2>

      <ul className="doc-refs">
        <li>
          <a href="https://aes2.org/publications/elibrary-page/?id=3271" target="_blank" rel="noopener noreferrer">Kaegi and Tempelaars, 1978</a>
          <span>VOSIM, a new sound synthesis system. Journal of the Audio Engineering Society 26(6), 418-425.</span>
          <a className="doc-ref-url" href="https://aes2.org/publications/elibrary-page/?id=3271" target="_blank" rel="noopener noreferrer">aes2.org/publications/elibrary-page/?id=3271</a>
        </li>
        <li>
          <a href="https://monoskop.org/log/?p=1343" target="_blank" rel="noopener noreferrer">Tempelaars, 1996</a>
          <span>Signal Processing, Speech and Music (ed.), Swets &amp; Zeitlinger. The definitions and the spectrum formula are in section 4.3 (pp. 137-138); the zero interval and parallel formants on p. 285; the recursive form in section 6.3 (p. 235).</span>
          <a className="doc-ref-url" href="https://monoskop.org/log/?p=1343" target="_blank" rel="noopener noreferrer">monoskop.org/log/?p=1343</a>
        </li>
        <li>
          <a href="https://csound.com/manual/opcodes/vosim/" target="_blank" rel="noopener noreferrer">Csound manual: vosim</a>
          <span>The opcode by Rasmus Ekman, 2008, with subtractive decay and a pulse-width factor.</span>
          <a className="doc-ref-url" href="https://csound.com/manual/opcodes/vosim/" target="_blank" rel="noopener noreferrer">csound.com/manual/opcodes/vosim</a>
        </li>
        <li>
          <a href="https://depts.washington.edu/dxscdoc/Help/Classes/VOSIM.html" target="_blank" rel="noopener noreferrer">SuperCollider: VOSIM</a>
          <span>The UGen by Léon Spek, in sc3-plugins.</span>
          <a className="doc-ref-url" href="https://depts.washington.edu/dxscdoc/Help/Classes/VOSIM.html" target="_blank" rel="noopener noreferrer">depts.washington.edu/dxscdoc/Help/Classes/VOSIM.html</a>
        </li>
        <li>
          <span className="doc-ref-name">Peterson and Barney, 1952</span>
          <span>Control methods used in a study of the vowels. Journal of the Acoustical Society of America 24(2), 175-184. The source of the approximate formant values of the vowel buttons.</span>
        </li>
      </ul>

    </div>;
}

export default Vosim;
